package hasaki.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ACCOUNT
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PHONENO
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String phoneno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TOKEN
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.GMT_CREATE
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.GMT_MODIFY
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.THIRDPARTY
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String thirdparty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.THIRDPARTYID
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String thirdpartyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.BIO
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.AVARTARURL
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private String avartarurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.FLOWCOUNT
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    private Integer flowcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ACCOUNT
     *
     * @return the value of user.ACCOUNT
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ACCOUNT
     *
     * @param account the value for user.ACCOUNT
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PHONENO
     *
     * @return the value of user.PHONENO
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PHONENO
     *
     * @param phoneno the value for user.PHONENO
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno == null ? null : phoneno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TOKEN
     *
     * @return the value of user.TOKEN
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TOKEN
     *
     * @param token the value for user.TOKEN
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.GMT_CREATE
     *
     * @return the value of user.GMT_CREATE
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.GMT_CREATE
     *
     * @param gmtCreate the value for user.GMT_CREATE
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.GMT_MODIFY
     *
     * @return the value of user.GMT_MODIFY
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.GMT_MODIFY
     *
     * @param gmtModify the value for user.GMT_MODIFY
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.THIRDPARTY
     *
     * @return the value of user.THIRDPARTY
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getThirdparty() {
        return thirdparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.THIRDPARTY
     *
     * @param thirdparty the value for user.THIRDPARTY
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setThirdparty(String thirdparty) {
        this.thirdparty = thirdparty == null ? null : thirdparty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.THIRDPARTYID
     *
     * @return the value of user.THIRDPARTYID
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getThirdpartyid() {
        return thirdpartyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.THIRDPARTYID
     *
     * @param thirdpartyid the value for user.THIRDPARTYID
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setThirdpartyid(String thirdpartyid) {
        this.thirdpartyid = thirdpartyid == null ? null : thirdpartyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.BIO
     *
     * @return the value of user.BIO
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.BIO
     *
     * @param bio the value for user.BIO
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.AVARTARURL
     *
     * @return the value of user.AVARTARURL
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public String getAvartarurl() {
        return avartarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.AVARTARURL
     *
     * @param avartarurl the value for user.AVARTARURL
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setAvartarurl(String avartarurl) {
        this.avartarurl = avartarurl == null ? null : avartarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.FLOWCOUNT
     *
     * @return the value of user.FLOWCOUNT
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public Integer getFlowcount() {
        return flowcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.FLOWCOUNT
     *
     * @param flowcount the value for user.FLOWCOUNT
     *
     * @mbg.generated Sat Mar 14 17:55:30 CST 2020
     */
    public void setFlowcount(Integer flowcount) {
        this.flowcount = flowcount;
    }
}