create table USER
(
	ID BIGINT auto_increment primary key not null,
	ACCOUNT VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONENO VARCHAR(100),
	NAME VARCHAR(50),
	TOKEN CHAR(36),
	GMT_CREATE BIGINT,
	GMT_MODIFY BIGINT,
	THIRDPARTY VARCHAR(50),
	THIRDPARTYID VARCHAR(50),
	BIO VARCHAR(256),
	PASSWORD VARCHAR(50),
	AVARTARURL VARCHAR(50),
	FOLLOW_COUNT INT DEFAULT 0 comment '关注者（被关注数）',
	QUESTION_COUNT INT DEFAULT 0 comment '问题数',
	ARTICLE_COUNT INT DEFAULT 0  comment '文章数'
);

